FROM hwdsl2/ipsec-vpn-server:latest

# COPY ไฟล์และให้ permission
COPY ipsec_server.sh /opt/src/ipsec_server.sh
RUN chmod 755 /opt/src/ipsec_server.sh

# ตรวจสอบแบบง่ายๆ
RUN ls -l /opt/src/ipsec_server.sh


### สำหรับ incoming traffic
# RUN iptables -t nat -A PREROUTING -p udp --dport 500 -j REDIRECT --to-port 30500
# RUN iptables -t nat -A PREROUTING -p udp --dport 4500 -j REDIRECT --to-port 34500

# ### สำหรับ outgoing traffic (ถ้าจำเป็น)
# RUN iptables -t nat -A OUTPUT -p udp --dport 500 -j REDIRECT --to-port 30500
# RUN iptables -t nat -A OUTPUT -p udp --dport 4500 -j REDIRECT --to-port 34500

# RUN iptables -t nat -L -n -v

CMD ["/opt/src/ipsec_server.sh"]