version: '3.8'

services:
  ipsec-server:
    image: hwdsl2/ipsec-vpn-server:latest
    container_name: ipsec-server
    # restart: unless-stopped
    environment:
      - VPN_IPSEC_PSK=1234567890
      - VPN_PUBLIC_IP=172.30.30.100
      - VPN_USER=testuser       
      - VPN_PASSWORD=testpassword   
      - VPN_SERVER_ID=@ipsec-server
      - VPN_DNS_SRV1=8.8.8.8
      - VPN_DNS_SRV2=1.1.1.1
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    privileged: true  
    ports:
      - "500:500/udp"    # IKE
      - "4500:4500/udp"  # NAT-T
    volumes:
      - ./ipsec_server.conf:/etc/ipsec.conf     
      # - ./ipsec_server.sh:/opt/src/run.sh 

    networks:
      net:
        ipv4_address: 172.30.30.100
      net-lan-a:
        ipv4_address: 172.20.0.10

# /opt/src/run.sh


  ipsec-client:
    # --- ✅ เปลี่ยนไปใช้ Image สำเร็จรูป ---
    image: fengzhou/ipsec-vpn-client:latest
    container_name: ipsec-client
    # restart: unless-stopped
    environment:
      - VPN_TYPE=ikev2
      - VPN_SERVER_IP=172.30.30.100       
      - VPN_IPSEC_PSK=1234567890
      - VPN_USER=testuser             
      - VPN_PASSWORD=testpassword     
      - VERBOSE=true
      - VPN_REMOTE_ID=@172.30.30.100 
      - VPN_ID=ipsec-client         
    cap_add:
      - NET_ADMIN
      - SYS_MODULE 
    privileged: true  
    volumes:
      - ./ipsec_client.conf:/etc/ipsec.conf
      # - ./ipsec_client.conf:/opt/src/ipsec.conf
      # - ./ipsec_client.sh:/opt/src/docker-entrypoint.sh

    
    networks:
      net:
        ipv4_address: 172.30.30.99
      net-lan-b:
        ipv4_address: 172.25.0.10




networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.30.0/24
  net-lan-a:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
  net-lan-b:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24